name: Update Firebase Rules

on:
  push:
    branches:
      - main

jobs:
  update-firebase-rules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Update Firebase Rules
      run: firebase database:rules:deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
